### ISSUE TITLE
Why are ruby recipies better than shell scripts?

### ISSUE THREAD

**Issue by blockjon** [flexera-public/rightscale_cookbooks#149]
Not sure where else to ask this... but the older RightScale way was to create & edit rightscripts directly in the RS interface. Why is there a huge move here to write everything as Ruby cookbooks? I don't understand why this is the new way... it seems a lot harder to deal with.

**Comment by arangamani** [comment]
@blockjon Please refer to: http://docs.opscode.com/chef_why.html for more information.
