### ISSUE TITLE
"Override Chef Cookbooks" link is broken in README

### ISSUE THREAD

**Issue by sonnysideup** [flexera-public/rightscale_cookbooks#155]
It looks like the link points to:

http://support.rightscale.com/12-Guides/Chef_Cookbooks_Developer_Guide/08-Chef_Development/Override_Chef_Cookbooks

but should actually point to:

http://support.rightscale.com/12-Guides/Chef_Cookbooks_Developer_Guide/04-Developer/ServerTemplate_Development/08-Common_Development_Tasks/Override_Chef_Cookbooks

**Comment by arangamani** [comment]
Hello @drywheat! Thanks for bringing this to our attention. We will no longer be using Cookbooks Override with the new Chef ServerTemplates development workflow. The documentation in the README has been updated internally and will be published as part of our next Maintenance Release.

**Comment by sonnysideup** [comment]
Good to know, I'll close this issue.
